const data = [
  { city1: "Katowice", city2: "Kraków", distance: 67 },
  { city1: "Szczecin", city2: "Gorzów Wielkopolski", distance: 73 },
  { city1: "Wrocław", city2: "Opole", distance: 81 },
  { city1: "Opole", city2: "Katowice", distance: 83 },
  { city1: "Bydgoszcz", city2: "Poznań", distance: 97 },
  { city1: "Kielce", city2: "Kraków", distance: 100 },
  { city1: "Warszawa", city2: "Łódź", distance: 104 },
  { city1: "Poznań", city2: "Gorzów Wielkopolski", distance: 109 },
  { city1: "Kraków", city2: "Rzeszów", distance: 112 },
  { city1: "Olsztyn", city2: "Gdańsk", distance: 114 },
  { city1: "Lublin", city2: "Rzeszów", distance: 114 },
  { city1: "Bydgoszcz", city2: "Gdańsk", distance: 116 },
  { city1: "Warszawa", city2: "Lublin", distance: 118 },
  { city1: "Poznań", city2: "Wrocław", distance: 127 },
  { city1: "Warszawa", city2: "Kielce", distance: 128 },
  { city1: "Wrocław", city2: "Katowice", distance: 129 },
  { city1: "Białystok", city2: "Warszawa", distance: 132 },
  { city1: "Katowice", city2: "Kielce", distance: 132 },
  { city1: "Łódź", city2: "Katowice", distance: 137 },
  { city1: "Opole", city2: "Kraków", distance: 138 },
  { city1: "Łódź", city2: "Kielce", distance: 139 },
  { city1: "Łódź", city2: "Poznań", distance: 143 },
  { city1: "Łódź", city2: "Wrocław", distance: 145 },
  { city1: "Kielce", city2: "Rzeszów", distance: 145 },
  { city1: "Lublin", city2: "Kielce", distance: 148 },
  { city1: "Katowice", city2: "Rzeszów", distance: 148 },
  { city1: "Bydgoszcz", city2: "Łódź", distance: 155 },
  { city1: "Olsztyn", city2: "Warszawa", distance: 161 },
  { city1: "Łódź", city2: "Opole", distance: 167 },
  { city1: "Poznań", city2: "Szczecin", distance: 168 },
  { city1: "Poznań", city2: "Opole", distance: 182 },
  { city1: "Bydgoszcz", city2: "Gorzów Wielkopolski", distance: 183 },
  { city1: "Wrocław", city2: "Kraków", distance: 183 },
  { city1: "Olsztyn", city2: "Bydgoszcz", distance: 187 },
  { city1: "Gorzów Wielkopolski", city2: "Wrocław", distance: 187 },
  { city1: "Lublin", city2: "Łódź", distance: 189 },
  { city1: "Warszawa", city2: "Katowice", distance: 193 },
  { city1: "Łódź", city2: "Kraków", distance: 193 },
  { city1: "Bydgoszcz", city2: "Wrocław", distance: 197 },
  { city1: "Gdańsk", city2: "Poznań", distance: 197 },
  { city1: "Warszawa", city2: "Poznań", distance: 198 },
  { city1: "Warszawa", city2: "Bydgoszcz", distance: 200 },
];

export const Białystok = [
  { city: "Warszawa", distance: 132 },
  { city: "Łódź", distance: 209 },
  { city: "Olsztyn", distance: 210 },
  { city: "Lublin", distance: 226 },
  { city: "Kielce", distance: 247 },
  { city: "Gdańsk", distance: 289 },
  { city: "Bydgoszcz", distance: 306 },
  { city: "Poznań", distance: 306 },
  { city: "Katowice", distance: 309 },
  { city: "Rzeszów", distance: 320 },
  { city: "Kraków", distance: 327 },
  { city: "Wrocław", distance: 333 },
  { city: "Opole", distance: 343 },
  { city: "GorzówWielkopolski", distance: 391 },
  { city: "Szczecin", distance: 448 },
];
export const Olsztyn = [
  { city: "Gdańsk", distance: 114 },
  { city: "Warszawa", distance: 161 },
  { city: "Bydgoszcz", distance: 187 },
  { city: "Białystok", distance: 210 },
  { city: "Łódź", distance: 211 },
  { city: "Lublin", distance: 263 },
  { city: "Poznań", distance: 268 },
  { city: "Kielce", distance: 273 },
  { city: "Katowice", distance: 316 },
  { city: "Wrocław", distance: 335 },
  { city: "Opole", distance: 350 },
  { city: "GorzówWielkopolski", distance: 353 },
  { city: "Kraków", distance: 353 },
  { city: "Rzeszów", distance: 355 },
  { city: "Szczecin", distance: 367 },
];
export const Warszawa = [
  { city: "Łódź", distance: 104 },
  { city: "Lublin", distance: 118 },
  { city: "Kielce", distance: 128 },
  { city: "Białystok", distance: 132 },
  { city: "Olsztyn", distance: 161 },
  { city: "Katowice", distance: 193 },
  { city: "Poznań", distance: 198 },
  { city: "Bydgoszcz", distance: 200 },
  { city: "Rzeszów", distance: 207 },
  { city: "Kraków", distance: 209 },
  { city: "Wrocław", distance: 225 },
  { city: "Opole", distance: 228 },
  { city: "Gdańsk", distance: 229 },
  { city: "GorzówWielkopolski", distance: 283 },
  { city: "Szczecin", distance: 340 },
];
export const Lublin = [
  { city: "Rzeszów", distance: 114 },
  { city: "Warszawa", distance: 118 },
  { city: "Kielce", distance: 148 },
  { city: "Łódź", distance: 189 },
  { city: "Kraków", distance: 211 },
  { city: "Białystok", distance: 226 },
  { city: "Katowice", distance: 248 },
  { city: "Olsztyn", distance: 263 },
  { city: "Bydgoszcz", distance: 286 },
  { city: "Poznań", distance: 287 },
  { city: "Wrocław", distance: 314 },
  { city: "Opole", distance: 319 },
  { city: "Gdańsk", distance: 341 },
  { city: "GorzówWielkopolski", distance: 372 },
  { city: "Szczecin", distance: 429 },
];
export const Bydgoszcz = [
  { city: "Poznań", distance: 97 },
  { city: "Gdańsk", distance: 116 },
  { city: "Łódź", distance: 155 },
  { city: "GorzówWielkopolski", distance: 183 },
  { city: "Olsztyn", distance: 187 },
  { city: "Wrocław", distance: 197 },
  { city: "Warszawa", distance: 200 },
  { city: "Szczecin", distance: 219 },
  { city: "Opole", distance: 254 },
  { city: "Katowice", distance: 258 },
  { city: "Kielce", distance: 262 },
  { city: "Lublin", distance: 286 },
  { city: "Białystok", distance: 306 },
  { city: "Kraków", distance: 312 },
  { city: "Rzeszów", distance: 380 },
];
export const Gdańsk = [
  { city: "Olsztyn", distance: 114 },
  { city: "Bydgoszcz", distance: 116 },
  { city: "Poznań", distance: 197 },
  { city: "Łódź", distance: 206 },
  { city: "Warszawa", distance: 229 },
  { city: "Szczecin", distance: 262 },
  { city: "GorzówWielkopolski", distance: 281 },
  { city: "Białystok", distance: 289 },
  { city: "Wrocław", distance: 295 },
  { city: "Katowice", distance: 311 },
  { city: "Kielce", distance: 314 },
  { city: "Lublin", distance: 341 },
  { city: "Opole", distance: 345 },
  { city: "Kraków", distance: 365 },
  { city: "Rzeszów", distance: 422 },
];
export const Łódź = [
  { city: "Warszawa", distance: 104 },
  { city: "Katowice", distance: 137 },
  { city: "Kielce", distance: 139 },
  { city: "Poznań", distance: 143 },
  { city: "Wrocław", distance: 145 },
  { city: "Bydgoszcz", distance: 155 },
  { city: "Opole", distance: 167 },
  { city: "Lublin", distance: 189 },
  { city: "Kraków", distance: 193 },
  { city: "Gdańsk", distance: 206 },
  { city: "Białystok", distance: 209 },
  { city: "Olsztyn", distance: 211 },
  { city: "GorzówWielkopolski", distance: 226 },
  { city: "Rzeszów", distance: 274 },
  { city: "Szczecin", distance: 282 },
];
export const Poznań = [
  { city: "Bydgoszcz", distance: 97 },
  { city: "GorzówWielkopolski", distance: 109 },
  { city: "Wrocław", distance: 127 },
  { city: "Łódź", distance: 143 },
  { city: "Szczecin", distance: 168 },
  { city: "Opole", distance: 182 },
  { city: "Gdańsk", distance: 197 },
  { city: "Warszawa", distance: 198 },
  { city: "Katowice", distance: 232 },
  { city: "Kielce", distance: 260 },
  { city: "Olsztyn", distance: 268 },
  { city: "Kraków", distance: 286 },
  { city: "Lublin", distance: 287 },
  { city: "Białystok", distance: 306 },
  { city: "Rzeszów", distance: 368 },
];
export const Szczecin = [
  { city: "GorzówWielkopolski", distance: 73 },
  { city: "Poznań", distance: 168 },
  { city: "Bydgoszcz", distance: 219 },
  { city: "Wrocław", distance: 247 },
  { city: "Gdańsk", distance: 262 },
  { city: "Łódź", distance: 282 },
  { city: "Opole", distance: 289 },
  { city: "Katowice", distance: 337 },
  { city: "Warszawa", distance: 340 },
  { city: "Olsztyn", distance: 367 },
  { city: "Kraków", distance: 391 },
  { city: "Kielce", distance: 402 },
  { city: "Lublin", distance: 429 },
  { city: "Białystok", distance: 448 },
  { city: "Rzeszów", distance: 473 },
];
export const GorzówWielkopolski = [
  { city: "Szczecin", distance: 73 },
  { city: "Poznań", distance: 109 },
  { city: "Bydgoszcz", distance: 183 },
  { city: "Wrocław", distance: 187 },
  { city: "Łódź", distance: 226 },
  { city: "Opole", distance: 229 },
  { city: "Katowice", distance: 278 },
  { city: "Gdańsk", distance: 281 },
  { city: "Warszawa", distance: 283 },
  { city: "Kraków", distance: 332 },
  { city: "Kielce", distance: 342 },
  { city: "Olsztyn", distance: 353 },
  { city: "Lublin", distance: 372 },
  { city: "Białystok", distance: 391 },
  { city: "Rzeszów", distance: 414 },
];
export const Wrocław = [
  { city: "Opole", distance: 81 },
  { city: "Poznań", distance: 127 },
  { city: "Katowice", distance: 129 },
  { city: "Łódź", distance: 145 },
  { city: "Kraków", distance: 183 },
  { city: "GorzówWielkopolski", distance: 187 },
  { city: "Bydgoszcz", distance: 197 },
  { city: "Warszawa", distance: 225 },
  { city: "Szczecin", distance: 247 },
  { city: "Kielce", distance: 252 },
  { city: "Rzeszów", distance: 265 },
  { city: "Gdańsk", distance: 295 },
  { city: "Lublin", distance: 314 },
  { city: "Białystok", distance: 333 },
  { city: "Olsztyn", distance: 335 },
];
export const Opole = [
  { city: "Wrocław", distance: 81 },
  { city: "Katowice", distance: 83 },
  { city: "Kraków", distance: 138 },
  { city: "Łódź", distance: 167 },
  { city: "Poznań", distance: 182 },
  { city: "Kielce", distance: 210 },
  { city: "Rzeszów", distance: 220 },
  { city: "Warszawa", distance: 228 },
  { city: "GorzówWielkopolski", distance: 229 },
  { city: "Bydgoszcz", distance: 254 },
  { city: "Szczecin", distance: 289 },
  { city: "Lublin", distance: 319 },
  { city: "Białystok", distance: 343 },
  { city: "Gdańsk", distance: 345 },
  { city: "Olsztyn", distance: 350 },
];
export const Katowice = [
  { city: "Kraków", distance: 67 },
  { city: "Opole", distance: 83 },
  { city: "Wrocław", distance: 129 },
  { city: "Kielce", distance: 132 },
  { city: "Łódź", distance: 137 },
  { city: "Rzeszów", distance: 148 },
  { city: "Warszawa", distance: 193 },
  { city: "Poznań", distance: 232 },
  { city: "Lublin", distance: 248 },
  { city: "Bydgoszcz", distance: 258 },
  { city: "GorzówWielkopolski", distance: 278 },
  { city: "Białystok", distance: 309 },
  { city: "Gdańsk", distance: 311 },
  { city: "Olsztyn", distance: 316 },
  { city: "Szczecin", distance: 337 },
];
export const Kielce = [
  { city: "Kraków", distance: 100 },
  { city: "Warszawa", distance: 128 },
  { city: "Katowice", distance: 132 },
  { city: "Łódź", distance: 139 },
  { city: "Rzeszów", distance: 145 },
  { city: "Lublin", distance: 148 },
  { city: "Opole", distance: 210 },
  { city: "Białystok", distance: 247 },
  { city: "Wrocław", distance: 252 },
  { city: "Poznań", distance: 260 },
  { city: "Bydgoszcz", distance: 262 },
  { city: "Olsztyn", distance: 273 },
  { city: "Gdańsk", distance: 314 },
  { city: "GorzówWielkopolski", distance: 342 },
  { city: "Szczecin", distance: 402 },
];
export const Kraków = [
  { city: "Katowice", distance: 67 },
  { city: "Kielce", distance: 100 },
  { city: "Rzeszów", distance: 112 },
  { city: "Opole", distance: 138 },
  { city: "Wrocław", distance: 183 },
  { city: "Łódź", distance: 193 },
  { city: "Warszawa", distance: 209 },
  { city: "Lublin", distance: 211 },
  { city: "Poznań", distance: 286 },
  { city: "Bydgoszcz", distance: 312 },
  { city: "Białystok", distance: 327 },
  { city: "GorzówWielkopolski", distance: 332 },
  { city: "Olsztyn", distance: 353 },
  { city: "Gdańsk", distance: 365 },
  { city: "Szczecin", distance: 391 },
];
export const Rzeszów = [
  { city: "Kraków", distance: 112 },
  { city: "Lublin", distance: 114 },
  { city: "Kielce", distance: 145 },
  { city: "Katowice", distance: 148 },
  { city: "Warszawa", distance: 207 },
  { city: "Opole", distance: 220 },
  { city: "Wrocław", distance: 265 },
  { city: "Łódź", distance: 274 },
  { city: "Białystok", distance: 320 },
  { city: "Olsztyn", distance: 355 },
  { city: "Poznań", distance: 368 },
  { city: "Bydgoszcz", distance: 380 },
  { city: "GorzówWielkopolski", distance: 414 },
  { city: "Gdańsk", distance: 422 },
  { city: "Szczecin", distance: 473 },
];
